### ISSUE TITLE
SPIKE: Can we trivially query the database?

### ISSUE THREAD

**Issue by Kelvinrr** [TeamSelene/BigDataVisualization#2]
Can we easily get an X by Y by Z cube of points from the database?

**Comment by Kelvinrr** [comment]
I have code written in python to connect and query the database along with notes on what it looks like.

**Comment by DanielOhn** [comment]
Where are the notes for this?

**Comment by Kelvinrr** [comment]
Sorry, just added it as part of the Wiki
