### ISSUE TITLE
As a client, I can graph reflectance 

### ISSUE THREAD

**Issue by Kelvinrr** [TeamSelene/BigDataVisualization#46]

**Comment by zowiehi** [comment]
Accidentally pushed directly to this repo. Changes in last commit add an example graph that is mapping random values against our reflection reference points. Chart created when point on map is clicked, we can pass the coordinates in a query to get the actual ref data for a point.

**Comment by zowiehi** [comment]
Ref1 data graphed as passed by geojson layer features

**Comment by zowiehi** [comment]
Ref1 data graphed as passed by geojson layer features
